# Generated by Django 5.1 on 2024-08-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_event_description_event_faculty_incharge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Organization',
            new_name='Association',
        ),
        migrations.AlterField(
            model_name='event',
            name='Permission',
            field=models.JSONField(default=dict),
        ),
    ]
