# Generated by Django 5.1 on 2024-08-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_event_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Faculty_Incharge',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='FeedBack',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='PO',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='Participations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='Student_Incharge',
            field=models.JSONField(default=dict),
        ),
    ]
