# Generated by Django 5.1 on 2024-08-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_alter_event_faculty_incharge_alter_event_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='Time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
