# Generated by Django 5.1 on 2024-08-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_event_date_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Resource_Person',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
