# Generated by Django 5.1 on 2024-08-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('RegNo', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Position', models.IntegerField(default=0)),
            ],
        ),
    ]
