# Generated by Django 5.1 on 2024-08-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0002_alter_log_email_alter_log_password_alter_log_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='Position',
            field=models.CharField(default='Student', max_length=100),
        ),
    ]
