# Generated by Django 5.1 on 2024-08-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0003_alter_log_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='Association',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
